### DISCUSSION TITLE
Enable syntax highlighting for Markdown code blocks

### DISCUSSION THREAD

**Discussion by jphalip** [standardnotes/forum#3137] [Suggestions]
When using Markdown, syntax highlighting doesn't appear to work. Except oddly just for HTML and XML:

<img width="454" alt="2023-03-03_20-43-16" src="https://user-images.githubusercontent.com/68544/222876217-cadc567f-902a-45e1-9d09-bf42990359ca.png">

**Describe the solution you'd like**

It'd be nice to enable syntax highlighting, similar to Github as you can see below:

```xml
<book>
  <title>The Catcher in the Rye</title>
  <author>J.D. Salinger</author>
  <genre>Novel</genre>
  <year>1951</year>
</book>
```

```html
<!DOCTYPE html>
<html>
  <head>
    <title>My Page</title>
  </head>
  <body>
    <h1>Welcome to my page!</h1>
    <p>This is some text.</p>
  </body>
</html>
```

```css
body {
  font-family: Arial, sans-serif;
  background-color: #f1f1f1;
}
```

```javascript
let num1 = 5;
let num2 = 10;
let sum = num1 + num2;
console.log(sum);
```

```python
name = input("What is your name? ")
print("Hello, " + name + "!")
```

```java
public class HelloWorld {
  public static void main(String[] args) {
    System.out.println("Hello, world!");
  }
}
```

```yaml
name: John Smith
age: 30
email: john.smith@example.com
```
