### ISSUE TITLE
Listed : show notes in grid format ? 

### ISSUE THREAD

**Issue by timconsidine** [standardnotes/forum#1086]
I would like to publish SN notes to Listed so they appear in a grid format, rather than horizontal listing

Is this possible ? With some CSS ?

New (paid) user of Standard Notes and very impressed with ease of use and functionality

**Comment by JaspalSuri** [comment]
Hi @timconsidine, 

Thanks for supporting us by subscribing to Extended and thank you for the kind words! 

You can use CSS to customize the appearance of your Listed blog. Please refer to [this document here](https://docs.standardnotes.org/listed/styles).

I've assigned this task to someone who might be better equipped to answer any specific CSS-related questions that you might have.

**Comment by timconsidine** [comment]
Thank you
I didn't see anything about a grid option for post listings
But I will await further comment

**Comment by mobitar** [comment]
You can view the page's source code (including CSS) for any author whose theme you like to see how they did it :)

**Comment by JaspalSuri** [comment]
> You can view the page's source code (including CSS) for any author whose theme you like to see how they did it :)

That's a good point. I've become so used to not being able to rely on that for certain websites that I almost forgot that we could do it on our own. :) 

Here's are some examples that a user on Slack shared:
- Bishop - https://listed.to/@Bishop
- Aether🌌  - https://aether.exposed/

Here's what Ben Montour (from our community Slack group) uses:

```css
---

metatype: css

---

:root {

	--background-color: #292937;

	--bio-color: var(--dimmed-text-color);

	--body-text-color: #d8d8d8;

	--dimmed-border-color: var(--dimmed-text-color);

	--dimmed-text-color: #7c7c7c;

	--header-author-name: var(--post-text-color);

	--header-border-color: var(--dimmed-text-color);

	--header-listed-name: var(--post-text-color);

	--link-color: #086dd6;

	--more-from-border-color: var(--dimmed-text-color);

	--page-menu-link-color: var(--post-text-color);

	/* --post-date-color: var(--dimmed-text-color); */

	--post-text-color: #d8d8d8;

	--post-title-color: var(--post-text-color);

	--website-color: var(--link-color);

}

html {

	overflow-x: hidden;

}

body {

	font-family: Consolas, courier, monospace;

	max-width: none;

	padding: 2%;

}

div#main-container {

	padding: 0.5rem;

	max-width: 1200px;

	margin: 0 auto;

}

/* Use Monospace for Headers and Titles */

.header-author-info, #page-header, h1, h2, h3 {

	font-family: monospace;

}

/* Leave a bit of space between sections */

h3 {

	margin-top: 1rem;

}

/* Material Style for Post Containers */

.post-content {

	background: #373E4F;

	padding: 1rem;

	border-radius: 5px;

	box-shadow: 0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24);

}

/* Styles for Inline Code Snippets */

code, .prettyprint {

	font-family: courier, monospace !important;

	font-size: 0.75rem;

	line-height: 0.75rem;

	color: #a2266c;

	padding: 4px 8px;

	background-color: #f7f7f9;

	border-radius: 3px;

}

/* Hide Post Body on Homepage, and Show in Full when Clicked */

.author-post .post-body {

	display: none;

}

/* Specify display for Homepage blog post grid */

div#author-posts {

	margin-top: 1rem;

	display: grid;

	grid-template-columns: repeat(auto-fill, minmax(14rem, 1fr));

}

div#author-posts::before {

	content: '';

	width: 0;

	grid-row: 1 / 1;

	grid-column: 1 / 1;

}

div#author-posts > *:first-child {

	grid-row: 1 / 1;

	grid-column: 1 / 1;

}

div.single-post-show.author-post {

	margin: 0.5rem !important;

	display: inline-block;

	vertical-align: top;

}

div.single-post-show.author-post .post-content {

	padding: 0.5rem;

	height: 100%;

	min-height: 140px;

	transition: all 0.3s cubic-bezier(.25,.8,.25,1);

}

div.single-post-show.author-post .post-content:hover {

	box-shadow: 0 3px 6px rgba(0,0,0,0.16), 0 3px 6px rgba(0,0,0,0.23);

}

div.single-post-show.author-post .post-content .post-date {

	position: absolute;

	bottom: 0;

	color: #7c7c7c;

}

div.single-post-show.author-post .post-content .post-title {

	font-weight: normal;

	font-size: 1.00rem;

}

.post-preview-body {

	display: none;

}

.header-author-info .word-count {

	display: none

}

#page-header .left .website-name {

	display: none

}

#page-header .left .author-name a {

	font-weight: bold;

	font-size: 1.50rem

}

#page-header .left .path-item:before {

	display: none

}

#page-header .left .path-item:nth-of-type(3) {

	display: none

}
```
