### ISSUE TITLE
Published notes formatting

### ISSUE THREAD

**Issue by nicolasduteil** [standardnotes/forum#120]
Hi. First, thanks for your work on this app :)

When publishing a note which was edited using "Advanced Markdown Editor", tables are not translated correctly to HTML in the published version. Also, while in the editor I tried to have to separate numbered list, there is only one in the published version

_Editor version_
![editor version](https://user-images.githubusercontent.com/5278949/32409083-22bebb68-c1a5-11e7-996b-110a82b2bc9d.png)

_Published version_
![published version](https://user-images.githubusercontent.com/5278949/32409084-26e60d5e-c1a5-11e7-973f-cec5a6e96299.png)

**Comment by mobitar** [comment]
Hey @nicolasduteil, indeed there are many different Markdown parsers, and each will have their own flavor. However, tables would be nice. I'll take a look at the Listed markdown parser and see if that's a possibility.

**Comment by RemiDesgrange** [comment]
Can you mark it as resolved ?

**Comment by nicolasduteil** [comment]
Hi. *Tables* are not correctly rendered in *published* version. Consecutive numbered list are still rendered as a single one (1,2,3,4)  in the *published* version instead of two different (1,2 ... 1,2) . This is a minor issue though.

*Editor version*

![Sélection_022](https://user-images.githubusercontent.com/5278949/65439214-19d52280-de27-11e9-975c-a7db8960838a.png)

*Published version*

![Sélection_023](https://user-images.githubusercontent.com/5278949/65439196-13df4180-de27-11e9-9355-6504518ba4d6.png)

**Comment by TheodoreChu** [comment]
Customizing the formatting for tables is available with [custom css](https://docs.standardnotes.org/listed/how-do-i-change-the-colors-fonts-and-general-layout-of-my-listed-blog). If you want tables formatted like they are on GitHub, you could add something like this:

```css
table {
  display: block;
  width: 100%;
  overflow: auto;
  margin-top: 0;
  margin-bottom: 16px;
  border-spacing: 0;
  border-collapse: collapse;

  tr {
    background-color: #fff;
    border-top: 1px solid #c6cbd1;  
  }

  td, th {
    padding: 6px 13px;
    border: 1px solid #dfe2e5;
  }

  tr:nth-child(2n) {
    background-color: #f6f8fa;
  }
}
```
This is an old issue, so I am closing it. Please open a new issue if you have any more problems. :wave:
