### ISSUE TITLE
Error when creating account ( arising )

### ISSUE THREAD

**Issue by quannghoang** [standardnotes/forum#1577]
When I create an account in : ' Create Account Free '
**The error message ' Cannot read properties of undefined ( reading 'digest' )** ' `#path ticker ( #1572 )`
Then following the instructions, I did put the web app behind an HTTPS certificate if using on same device.

**Appears : 'unknown error'**

What step did I do wrong ?
Please help me, thank you very much !
<img width="658" alt="image" src="https://user-images.githubusercontent.com/97494537/161680726-5c000708-60f3-4f91-9f89-029b193ed560.png">

**Comment by lfloresbatista** [comment]
> When I create an account in : ' Create Account Free ' **The error message ' Cannot read properties of undefined ( reading 'digest' )** ' `#path ticker ( #1572 )` Then following the instructions, I did put the web app behind an HTTPS certificate if using on same device.
> 
> **Appears : 'unknown error'**
> 
> What step did I do wrong ? Please help me, thank you very much ! <img alt="image" width="658" src="https://user-images.githubusercontent.com/97494537/161680726-5c000708-60f3-4f91-9f89-029b193ed560.png">

You just need to map the 3000 port and type in the custom sync server http://localhost:3000 if your using snotes locally.

for example, the mapping:

```
#docker-compose.yml
#...
services:
  server:
    image: standardnotes/server
    container_name: sersnotes_server
    hostname: snotes
    restart: unless-stopped
    env_file: .env
    ports:
      - 3000:3000
      - 3125:3104
 #...
```
and in the app, this:
![image](https://github.com/standardnotes/forum/assets/97482694/18c55a62-3e24-4835-9e18-6ae9fbfee29b)

thats it.
