### ISSUE TITLE
[Help Wanted] 2FA setup is broken, api-gateway errors, Auth Server has problems

### ISSUE THREAD

**Issue by MFYDev** [standardnotes/forum#3241]
**Describe the bug**
I am using 1Password as my password manager now, and I am self hosting the profession version of Standard Notes on my own server. All container's timezone has been set as America/New_York as my machine timezone. However, after I log in and go to settings, try to enable 2FA, everytime on Step 3 I will encounter this issue, Incorrect secret key, please try again.

**To Reproduce**
1. Go to 'Settings' -> Security
2. Click on 'Two-factor authentication'
3. copy the secret key and input the one time password generated by 1Password

**Expected behavior**
2FA should be set up without errors

**Screenshots**
<img width="643" alt="image" src="https://github.com/standardnotes/forum/assets/53750381/213a09db-f514-4607-8596-3901475cad53">

in the log, it shows:
==> logs/api-gateway.log <==
{"level":"error","message":"Could not pass the request to http://localhost:3103/users/142c2fd3-7e2b-4aec-9317-5e88f8e20229/settings on underlying service: {\"error\":{\"message\":\"Unfortunately, we couldn't handle your request. Please try again or contact our support if the error persists.\"}}","service":"api-gateway"}

**Desktop (please complete the following information):**
 - OS: MacOS and Web
 - Browser Edge
 - Version Latest

**Comment by MFYDev** [comment]
Also here is a bug report same as me #1518
And this: https://github.com/standardnotes/server/issues/476

**Comment by MFYDev** [comment]
""
localhost:3101 is unavailable yet - waiting for it to start
localhost:3101 is unavailable yet - waiting for it to start
localhost:3101 is unavailable yet - waiting for it to start
localhost:3101 is up. Proceeding to startup.
{"level":"info","message":"Server started on port 3000","service":"api-gateway"}
{"level":"error","message":"Could not pass the request to http://localhost:3103/auth on underlying service: undefined","service":"api-gateway"}
localhost:3101 is unavailable yet - waiting for it to start
localhost:3101 is up. Proceeding to startup.
{"level":"info","message":"Server started on port 3000","service":"api-gateway"}
{"level":"error","message":"Could not pass the request to http://localhost:3103/users/b402624a-7faf-4142-be7b-efba3dce980f/settings on underlying service: {\"error\":{\"message\":\"Unfortunately, we couldn't handle your request. Please try again or contact our support if the error persists.\"}}","service":"api-gateway"}
{"level":"error","message":"Could not pass the request to http://localhost:3103/users/b402624a-7faf-4142-be7b-efba3dce980f/settings on underlying service: {\"error\":{\"message\":\"Unfortunately, we couldn't handle your request. Please try again or contact our support if the error persists.\"}}","service":"api-gateway"}
localhost:3101 is unavailable yet - waiting for it to start
localhost:3101 is up. Proceeding to startup.
{"level":"info","message":"Server started on port 3000","service":"api-gateway"}
{"level":"error","message":"Could not pass the request to sessions/validate on underlying service: undefined","service":"api-gateway"}
{"level":"error","message":"Could not pass the request to sessions/validate on underlying service: undefined","service":"api-gateway"}
{"level":"error","message":"Could not pass the request to sessions/validate on underlying service: undefined","service":"api-gateway"}
{"level":"error","message":"Could not pass the request to sessions/validate on underlying service: undefined","service":"api-gateway"}
{"level":"error","message":"Could not pass the request to sessions/validate on underlying service: undefined","service":"api-gateway"}
{"level":"error","message":"Could not pass the request to sessions/validate on underlying service: undefined","service":"api-gateway"}
{"level":"error","message":"Could not pass the request to http://localhost:3103/users/b402624a-7faf-4142-be7b-efba3dce980f/settings on underlying service: {\"error\":{\"message\":\"Unfortunately, we couldn't handle your request. Please try again or contact our support if the error persists.\"}}","service":"api-gateway"}
localhost:3101 is unavailable yet - waiting for it to start
localhost:3101 is up. Proceeding to startup.
{"level":"info","message":"Server started on port 3000","service":"api-gateway"}
localhost:3101 is unavailable yet - waiting for it to start
localhost:3101 is up. Proceeding to startup.
{"level":"info","message":"Server started on port 3000","service":"api-gateway"}
localhost:3101 is unavailable yet - waiting for it to start
localhost:3101 is up. Proceeding to startup.
{"level":"info","message":"Server started on port 3000","service":"api-gateway"}
localhost:3101 is unavailable yet - waiting for it to start
localhost:3101 is up. Proceeding to startup.
{"level":"info","message":"Server started on port 3000","service":"api-gateway"}
localhost:3101 is unavailable yet - waiting for it to start
localhost:3101 is up. Proceeding to startup.
{"level":"info","message":"Server started on port 3000","service":"api-gateway"}
localhost:3101 is unavailable yet - waiting for it to start
localhost:3101 is up. Proceeding to startup.
{"level":"info","message":"Server started on port 3000","service":"api-gateway"}
{"level":"error","message":"Could not pass the request to http://localhost:3103/users/b402624a-7faf-4142-be7b-efba3dce980f/settings on underlying service: {\"error\":{\"message\":\"Unfortunately, we couldn't handle your request. Please try again or contact our support if the error persists.\"}}","service":"api-gateway"}
{"level":"error","message":"Could not pass the request to http://localhost:3103/users/b402624a-7faf-4142-be7b-efba3dce980f/settings on underlying service: {\"error\":{\"message\":\"Unfortunately, we couldn't handle your request. Please try again or contact our support if the error persists.\"}}","service":"api-gateway"}
{"level":"error","message":"Could not pass the request to http://localhost:3103/users/b402624a-7faf-4142-be7b-efba3dce980f/settings on underlying service: {\"error\":{\"message\":\"Unfortunately, we couldn't handle your request. Please try again or contact our support if the error persists.\"}}","service":"api-gateway"}
{"level":"error","message":"Could not pass the request to http://localhost:3103/users/b402624a-7faf-4142-be7b-efba3dce980f/settings on underlying service: {\"error\":{\"message\":\"Unfortunately, we couldn't handle your request. Please try again or contact our support if the error persists.\"}}","service":"api-gateway"}
"""

Just more log details for api-gateway

**Comment by karolsojko** [comment]
Hi @MFYDev 

can we get a log from the auth service? Apparently it didn't start thus API-Gateway is saying that it couldn't pass the request to it. If we could see the auth service logs then we'll know what the root cause of this is

**Comment by MFYDev** [comment]
@karolsojko The problem is there is no error on auth

![image](https://github.com/standardnotes/forum/assets/53750381/fbc048bc-c250-48c3-8730-b231be65608e)
![image](https://github.com/standardnotes/forum/assets/53750381/4ea327ad-820d-468c-9579-e2b434af65bc)
![image](https://github.com/standardnotes/forum/assets/53750381/65a87db0-fb48-4c3f-a61d-6430f766ac2b)

**Comment by karolsojko** [comment]
@MFYDev can you set in your `.env` file `AUTH_SERVER_LOG_LEVEL=debug` and check what is there in the auth logs when you make that specific request ?

**Comment by fame-odoo** [comment]
yeah sure, 

Here is the debug log

![image](https://github.com/standardnotes/forum/assets/107050396/a97f6804-e5f0-443f-ad33-1bdee7cb372c)
![image](https://github.com/standardnotes/forum/assets/107050396/ca210341-f259-4889-a9fc-6eec045b6d8b)
![image](https://github.com/standardnotes/forum/assets/107050396/91028c2a-e4be-4d91-9431-38daf0e5485e)
![image](https://github.com/standardnotes/forum/assets/107050396/2aa31f75-3a83-4642-a7f5-7f133bfc5ef7)


Is there anything wrong that maybe related to the nginx reverse proxy?
I am running Standardnotes Server behind a nginx reverse proxy, here below is the config

#PROXY-START/

location ^~ /
{
    proxy_pass http://localhost:9870;
    proxy_set_header Host mydomain;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header REMOTE-HOST $remote_addr;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_http_version 1.1;
}

#PROXY-END/

**Comment by fame-odoo** [comment]
![image](https://github.com/standardnotes/forum/assets/107050396/f412c082-a61a-44e7-9438-61b1999c8d6f)


Here is the log of all. I ran again

**Comment by fame-odoo** [comment]
Seems like 
==> auth.log <==
{"level":"debug","message":"Could not decode token with primary decoder, trying fallback decoder.","service":"auth"}
query: SELECT `session`.`uuid` AS `session_uuid`, `session`.`user_uuid` AS `session_user_uuid`, `session`.`hashed_access_token` AS `session_hashed_access_token`, `session`.`hashed_refresh_token` AS `session_hashed_refresh_token`, `session`.`access_expiration` AS `session_access_expiration`, `session`.`refresh_expiration` AS `session_refresh_expiration`, `session`.`api_version` AS `session_api_version`, `session`.`user_agent` AS `session_user_agent`, `session`.`created_at` AS `session_created_at`, `session`.`updated_at` AS `session_updated_at`, `session`.`readonly_access` AS `session_readonly_access` FROM `sessions` `session` WHERE `session`.`uuid` = ? -- PARAMETERS: ["c46414d3-ebf2-4c6c-b579-8dd8baca8514"]
{"level":"debug","message":"Token decoded successfully. Session found.","service":"auth"}
query: SELECT `user`.`uuid` AS `user_uuid`, `user`.`version` AS `user_version`, `user`.`email` AS `user_email`, `user`.`pw_nonce` AS `user_pw_nonce`, `user`.`encrypted_server_key` AS `user_encrypted_server_key`, `user`.`server_encryption_version` AS `user_server_encryption_version`, `user`.`kp_created` AS `user_kp_created`, `user`.`kp_origination` AS `user_kp_origination`, `user`.`pw_cost` AS `user_pw_cost`, `user`.`pw_key_size` AS `user_pw_key_size`, `user`.`pw_salt` AS `user_pw_salt`, `user`.`pw_alg` AS `user_pw_alg`, `user`.`pw_func` AS `user_pw_func`, `user`.`encrypted_password` AS `user_encrypted_password`, `user`.`created_at` AS `user_created_at`, `user`.`updated_at` AS `user_updated_at`, `user`.`locked_until` AS `user_locked_until`, `user`.`num_failed_attempts` AS `user_num_failed_attempts` FROM `users` `user` WHERE `user`.`uuid` = ? -- PARAMETERS: ["b402624a-7faf-4142-be7b-efba3dce980f"]
query: SELECT `roles`.`uuid` AS `roles_uuid`, `roles`.`name` AS `roles_name`, `roles`.`version` AS `roles_version`, `roles`.`created_at` AS `roles_created_at`, `roles`.`updated_at` AS `roles_updated_at` FROM `roles` `roles` INNER JOIN `user_roles` `user_roles` ON `user_roles`.`user_uuid` IN (?) AND `user_roles`.`role_uuid`=`roles`.`uuid` -- PARAMETERS: ["b402624a-7faf-4142-be7b-efba3dce980f"]

This means the auth server cannot decode token right?

**Comment by karolsojko** [comment]
Yes, here's the error in your logs:
```
{"level":"error", "message":"Error: Unsupported state or unable to authenticate data\n at Decipheriv. final (node: internal/crypto/cipher: 199:29)In at CryptoNode.aes256GcmDecrypt/opt/bundled/auth/packages/sncrypto-node/dist/src/CryptoNode.js:23:103)In at Crypter Node.decryptUserServerKey/opt/bundled/auth/packages/auth/dist/src/Domain/Encryption/CrypterNode.is:71:32)\n at CrypterNode.encryptForUser/opt/bundled/auth/packages/auth/dist/src/Domain/Encryption/CrypterNode.is:42:51\n at SettingFactory.createValue /opt/bund led/auth/packages/auth/dist/src/Domain/Setting/SettingFactory.js:90:37)In at SettingFactory.create/opt/bundled/auth/packages/auth/dist/src/Domain/Setting/SettingFactory.js:67:31)In at SettingService.createOrReplace/opt/bundled/auth/packages/auth/dist/src/Domai n/Setting/SettingService. js: 82:82) \n at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n at async UpdateSetting.execute (/opt/bundled/auth/packages/auth/dist/src/Domain/UseCase/UpdateSetting/UpdateSetting.js:112:26)\n tedSettingsController.updateSetting(/opt/bundled/auth/packages/auth/dist/src/Infra/InversifyExpressUtils/Base/BaseSettingsController.js:85:24)","service":"auth"}
```

The reason for this is that your data has been encrypted with one secret and now there is an attempt to decrypt it with another secret.

Root cause is the same as in here: https://github.com/standardnotes/server/issues/476

Please update your server and env file. Set your keys in the `.env` according to the instructions in here: https://standardnotes.com/help/self-hosting/docker

**Comment by fame-odoo** [comment]
Hi, thank you! but I am doing a whole new install and I checked the docker-compose and env file for multiple times, according to what you said, 
https://github.com/standardnotes/server/issues/476#issuecomment-1470150820
There is no legacy for me because this is a whole new install by using the latest file.

And here below is the docker-compose and the env:

.env


```
######
# DB #
######

DB_HOST=db
DB_PORT=3306
DB_USERNAME=std_notes_user
DB_PASSWORD=hidden
DB_DATABASE=standard_notes_db
DB_TYPE=mysql

#########
# CACHE #
#########

REDIS_PORT=6379
REDIS_HOST=cache
CACHE_TYPE=redis

########
# KEYS #
########

AUTH_JWT_SECRET=hiddenforsecurity
AUTH_SERVER_ENCRYPTION_SERVER_KEY=hiddenforsecurity
VALET_TOKEN_SECRET=hiddenforsecurity

PUBLIC_FILES_SERVER_URL=https://hiddenforsecurity
AUTH_SERVER_DISABLE_USER_REGISTRATION=true
AUTH_SERVER_LOG_LEVEL=debug
```

The 3 secrets are not the same

And here below is my docker-compose.yml

```
services:
  server:
    image: standardnotes/server
    env_file: .env
    container_name: standardnotes-server
    restart: always
    ports:
      - 9870:3000
      - 9871:3104
    volumes:
      - ./logs:/var/lib/server/logs
      - ./uploads:/opt/bundled/files/packages/files/dist/uploads
    networks:
      - standardnotes_self_hosted

  localstack:
    image: localstack/localstack:1.3
    container_name: standardnotes-localstack
    expose:
      - 4566
    restart: always
    environment:
      - SERVICES=sns,sqs
      - HOSTNAME_EXTERNAL=localstack
      - LS_LOG=warn
    volumes:
      - ./localstack_bootstrap.sh:/etc/localstack/init/ready.d/localstack_bootstrap.sh
    networks:
      - standardnotes_self_hosted

  db:
    image: mysql:8
    container_name: standardnotes-db
    environment:
      - MYSQL_DATABASE=standard_notes_db
      - MYSQL_USER=std_notes_user
      - MYSQL_ROOT_PASSWORD=hidden
      - MYSQL_PASSWORD=hidden
    expose:
      - 3306
    restart: always
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./data/import:/docker-entrypoint-initdb.d
    networks:
      - standardnotes_self_hosted

  cache:
    image: redis:6.0-alpine
    container_name: standardnotes-cache
    volumes:
      - ./data/redis/:/data
    expose:
      - 6379
    restart: always
    networks:
      - standardnotes_self_hosted

networks:
  standardnotes_self_hosted:
    name: standardnotes_self_hosted
```
