### ISSUE TITLE
SHA512 checksums only available for AppImage in Linux releases for version 3.197.0

### ISSUE THREAD

**Issue by taivlam** [standardnotes/forum#3956]
**Describe the bug**
SHA512 checksums are only available for AppImage in Linux releases for [version 3.197.0](https://github.com/standardnotes/app/releases/tag/%40standardnotes%2Fdesktop%403.197.0) when `latest-linux.yml` and `latest-linux-arm64.yml` are inspected.

**To Reproduce**
1. Go to the [Desktop 3.197.0](https://github.com/standardnotes/app/releases/tag/%40standardnotes%2Fdesktop%403.197.0) release.
2. Download either `latest-linux.yml` or `latest-linux-arm64.yml`.
3. Open either YAML file with a text editor.
4. See that only SHA512 checksums are available for AppImage releases.

**Expected behavior**
There should be more types of releases for Linux, including DEB archives.

**Screenshots(/Raw Text)**
This is the raw text content for `latest-linux.yml`:
```
version: 3.197.0
files:
  - url: standard-notes-3.197.0-linux-x86_64.AppImage
    sha512: /hhtKaqY8jvm7YcAtC+5PUhfbvQzej5it5aVgnT5Dlfs+6L3NYLhGgTqprJODhJCMlZQ00MuyNHrr9tRVIVgwQ==
    size: 166644437
    blockMapSize: 174825
path: standard-notes-3.197.0-linux-x86_64.AppImage
sha512: /hhtKaqY8jvm7YcAtC+5PUhfbvQzej5it5aVgnT5Dlfs+6L3NYLhGgTqprJODhJCMlZQ00MuyNHrr9tRVIVgwQ==
releaseDate: '2025-06-16T11:41:50.933Z'
```

This is the raw text content in `latest-linux-arm64.yml`:
```
version: 3.197.0
files:
  - url: standard-notes-3.197.0-linux-arm64.AppImage
    sha512: oEX83sFtgP3n6raXcx8bu/lPfeJYr3H40f6xI+Y1Jv69XiHZGKHTdEOJf3PbMCcSQ2YF5ZpImDVToqHOpBTNmQ==
    size: 167851295
    blockMapSize: 176235
path: standard-notes-3.197.0-linux-arm64.AppImage
sha512: oEX83sFtgP3n6raXcx8bu/lPfeJYr3H40f6xI+Y1Jv69XiHZGKHTdEOJf3PbMCcSQ2YF5ZpImDVToqHOpBTNmQ==
releaseDate: '2025-06-16T11:42:24.404Z'
```

**Desktop (please complete the following information):**
 - OS: Pop!\_OS 22.04 and Pop!\_OS 24.04 Alpha 7
 - Browser: N/A (as this is the native desktop client via DEB archive)
 - Version: 3.197.0

**Additional context**
I maintain `standard-notes-bin` on the [MPR](https://mpr.makedeb.org/packages/standard-notes-bin#package-details).  I noticed that now the GH releases area indicated that version 3.197.0 is now the stable release for native desktop clients on June 16, 2025 (about 10 days ago).  I was also alerted to an update after an alert through [Repology](https://repology.org/project/standard-notes/versions).

In prior stable releases until version 3.197.0, SHA512 checksums were offered and "auto-generated" for all the Linux releases available for Standard Notes.
